name: Build Flutter APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Installer Flutter (version FIXE pour éviter tes erreurs)
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.7'
          channel: stable

      # 3. Vérifier Flutter
      - name: Flutter doctor
        run: flutter doctor

      # 4. Installer les dépendances
      - name: Install dependencies
        run: flutter pub get

      # 5. Tests (optionnel mais propre)
      - name: Analyze project
        run: flutter analyze

      # 6. Build APK release
      - name: Build APK
        run: flutter build apk --release

      # 7. Upload APK (VERSION CORRECTE v4)
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
